### ISSUE TITLE
Comments on privacy policy

### ISSUE THREAD

**Issue by r0one** [lvaroqui/pae-website#6]
Hi Luc,
There is no link pointing to a privacy policy. If it exist, you should make it easy to find. It it doesn't, I would be glad to contribute :)

**Comment by r0one** [comment]
Update: a privacy policy has been added

**Comment by lvaroqui** [comment]
It is now accessible by clicking on "Politique de Confidentialité" on the footer. See ef83521eff3516f6282ffbfa5f0ddeca67e89330
Any comments/remarks are welcomed !

**Comment by r0one** [comment]
> Communication à des tiers
Aucune des informations dont il est mention ci-dessus n'est communiquée à des tiers.
Hébergement
Ce site est hébergé par Luc Varoqui pour le PAE UTC. Pour toute question, merci de prendre contact à l'adresse poleae@assos.utc.fr. 

This is incoherent. If the data is stored by somebody that is not PAE-UTC, then the data is transmitted to a third party (Luc Varoqui).

**Comment by r0one** [comment]
By the way, it looks like the data is stored on OVH, the GDPR makes it mandatory to provide the full subcontractor chain

**Comment by lvaroqui** [comment]
Fixed with #8
