### ISSUE TITLE
Users should be able to mask their name on bookings

### ISSUE THREAD

**Issue by r0one** [lvaroqui/pae-website#7]
It is not necessary that users have the ability to see the name of other users making bookings. Only the PAE must see the names in order to administrate the rooms.

We either :

- let the user decide whether he wants to display his name on the booking or not

- or mask the name on all bookings

**Comment by r0one** [comment]
But we could make it mandatory for associations as it is not a personal data.

**Comment by lvaroqui** [comment]
Fixed with #8
